spring:
  datasource:
    url: jdbc:sqlserver://sny-server.database.windows.net:1433
    username: sny
    password: Anand@123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect : org.hibernate.dialect.SQLServer2012Dialect

server:
  port: 9191


